# Generated by Django 4.1.7 on 2023-02-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Author'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Comment author')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('body', models.TextField(db_index=True, max_length=2000, verbose_name='Comment body')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Publication date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
